import { useEffect, useState } from "react";
import { BarChart3 } from "lucide-react";
import { getLatestEvaluation } from "../lib/api";
import type { EvaluationReport } from "../types";

const METRIC_LABELS: Record<string, string> = {
  source_retrieval_success: "Source retrieval",
  provenance_validity: "Provenance validity",
  evidence_grounding_rate: "Evidence grounding",
  evidence_type_correctness: "Evidence-type correctness",
  cross_source_consistency: "Cross-source consistency",
  conflict_detection: "Conflict detection",
  abstention_correctness: "Abstention correctness",
  tool_recovery_success: "Tool recovery",
  unsupported_claim_rate: "Unsupported claim rate",
  end_to_end_success: "End-to-end success",
};

function fmt(v: number | null): string {
  return v === null ? "NOT EVALUATED" : `${(v * 100).toFixed(1)}%`;
}

export function ReliabilityPanel() {
  const [report, setReport] = useState<EvaluationReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getLatestEvaluation()
      .then(setReport)
      .catch((err) => setError(err instanceof Error ? err.message : String(err)))
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="bg-panel-light border border-line rounded-xl p-4">
      <div className="flex items-center gap-1.5 mb-1">
        <BarChart3 className="w-3.5 h-3.5 text-teal" />
        <h3 className="text-xs font-bold text-ink uppercase tracking-wide">Evaluation benchmark</h3>
      </div>
      <p className="text-[10px] text-muted-ink mb-2.5">
        Precomputed reliability results from{" "}
        <span className="font-mono">curie/evaluation/results/latest.json</span> —
        generated by <span className="font-mono">python -m curie.evaluation.runner</span>,
        not calculated from the sequence above. See{" "}
        <span className="font-mono">curie/evaluation/README.md</span>.
      </p>

      {loading && <p className="text-[11px] text-muted-ink">Loading evaluation results...</p>}
      {error && (
        <p className="text-[11px] text-amber">
          Evaluation results unavailable ({error}). Run{" "}
          <span className="font-mono">python -m curie.evaluation.runner</span> to generate them.
        </p>
      )}
      {report && (
        <>
          <div className="text-[9.5px] text-muted-ink mb-2">
            {report.cases_evaluated} scientific case(s), {report.scenarios_evaluated} reliability scenario(s) ·
            generated {new Date(report.run_timestamp).toLocaleString()}
          </div>
          <div className="grid grid-cols-2 gap-1.5">
            {Object.entries(report.metrics).map(([key, value]) => (
              <div key={key} className="flex justify-between text-[10.5px] border-b border-line/50 py-1">
                <span className="text-muted-ink">{METRIC_LABELS[key] ?? key}</span>
                <span className={`font-mono font-semibold ${value === null ? "text-muted-ink" : "text-ink"}`}>
                  {fmt(value)}
                </span>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );
}
